---
apiVersion: v1
kind: Service
metadata:
  name: hello-python
  namespace: ingress
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080  # Porta do container
    protocol: TCP
  selector:
    app: hello-python